### ISSUE TITLE
The stack fails at last stage due to custom key store failing to connect with HSM cluster

### ISSUE THREAD

**Issue by awspankj** [aws-samples/aws-cloudhsm-cloudformation-template#12]
When you choose to create custom key store, the stack gets stuck for more than 1.5 hours and then rolls back. The custom key store gets created but fails  to connect  with HSM cluster with error- "KMS cannot connect the custom key store to its CloudHSM cluster. Error code: USER_NOT_FOUND". I assume 'kmsuser' is not getting configured correctly.

**Comment by ckamps** [comment]
@awspankj thanks for the report. We're in the process of preparing a heavily refactored version of this automation for publishing here in aws-samples. In the meantime, did you get a chance to inspect the `cfn-init.log` data to potentially better understand the issue? As mentioned in [Troubleshooting stack creation](  https://github.com/aws-samples/aws-cloudhsm-cloudformation-template#troubleshooting-stack-creation). 

I've also provided you separately with a pointer to the heavily refactored fork in case you'd like to try that version.

**Comment by ckamps** [comment]
@awspankj it appears that the `kmsuser` was created, but at the point that the CloudHSM key store was being connected, the `kmuser` is in an `inconsistent` state. i.e. the user is not present on each of the two HSMs in the cluster. The connect operation fails due to the user not being present in all HSMs of the cluster.

I'm investigating why, under some circumstances, the user gets into that state. This failure appears to be a result of enhancing the code to use the `cloudhsm-cli` package vs the `cloudhsm-client` package.

**Comment by awspankj** [comment]
Hi @Christopher ***@***.***> Thanks for the update. This is interesting  and something new I learned.

After the stack was failing in the end, I learned to do it manually with latest cloudhsm CLI commands + console – attached are the steps.

Hope to see the github version working again!  Meanwhile I will test the fork version.

Warm Regards,
Pankaj Patil
Partner Solutions Architect WWPS
Mob- +919967936244

From: Christopher Kampmeier ***@***.***>
Reply to: aws-samples/aws-cloudhsm-cloudformation-template ***@***.***>
Date: Saturday, 13 May 2023 at 3:56 AM
To: aws-samples/aws-cloudhsm-cloudformation-template ***@***.***>
Cc: "Patil, Pankaj" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-samples/aws-cloudhsm-cloudformation-template] The stack fails at last stage due to custom key store failing to connect with HSM cluster (Issue #12)


@awspankj<https://github.com/awspankj> it appears that the kmsuser was created, but at the point that the CloudHSM key store was being connected, the kmuser is in an inconsistent state. i.e. the user is not present on each of the two HSMs in the cluster. The connect operation fails due to the user not being present in all HSMs of the cluster.

I'm investigating why, under some circumstances, the user gets into that state. This failure appears to be a result of enhancing the code to use the cloudhsm-cli package vs the cloudhsm-client package.

**Comment by ckamps** [comment]
@awspankj I reverted this repository to the changes prior to introducing use of the `cloudhsm-cli` package in place of the `cloudhsm-client` package so that the `kmsuser` creation is stable. I'll send a note to you once the newly refactored form of the overall automation is published to this repository. In the meantime, you can use the internal fork I referenced separately.

**Comment by awspankj** [comment]
@Christopher ***@***.***> I gave it a try just now:



  1.  The stack completed  (with parameter ‘custom key store’)
  2.  Cluster is in active state. However, Custom key store is not created.




***@***.***



  1.  The Kmsuser is not created

***@***.***


  1.  Creation of kmsuser succeeds when done manually:


***@***.***


  1.  Now using the kmsuser and anchor certificate stored  in secrets manager, custom key store is created from aws console.

***@***.***


Warm Regards,
Pankaj Patil
Partner Solutions Architect WWPS
Mob- +919967936244

From: Christopher Kampmeier ***@***.***>
Reply to: aws-samples/aws-cloudhsm-cloudformation-template ***@***.***>
Date: Sunday, 14 May 2023 at 9:43 PM
To: aws-samples/aws-cloudhsm-cloudformation-template ***@***.***>
Cc: "Patil, Pankaj" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-samples/aws-cloudhsm-cloudformation-template] The stack fails at last stage due to custom key store failing to connect with HSM cluster (Issue #12)


@awspankj<https://github.com/awspankj> I reverted this repository to the changes prior to introducing use of the cloudhsm-cli package in place of the cloudhsm-client package so that the kmsuser creation is stable. I'll send a note to you once the newly refactored form of the overall automation is published to this repository. In the meantime, you can use the internal fork I referenced separately.
